version: '3'

networks:
    main_net:

services:
    nginx: 
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./services/nginx
        ports:
          - 3050:80
        depends_on:
          - django
          - cubejs
        networks:
            - main_net

    django:
        stdin_open: true
        build: 
            context: ./services/envglobeldjango
            dockerfile: Dockerfile.dev
        command: ["python","manage.py","runserver", "0.0.0.0:8000"]
        volumes:
            - "./services/envglobeldjango:/api"
        environment:
            PYTHONPATH: /api
            PYTHONUNBUFFERED: "True"
            DEBUG: "True"
        env_file: ./services/envglobeldjango/.env
        networks:
            - main_net
    cubejs:
        build: 
            context: ./services/cubejs
            dockerfile: Dockerfile.dev
        env_file:
            - ./services/cubejs/.env
        volumes:
            - ./services/cubejs:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - main_net

    api_ml:
        build:
            context: ./services/api_ml
            dockerfile: Dockerfile
        volumes: 
            - ./services/api_ml:/app

    frontend:
        stdin_open: true
        build: 
            context: ./services/envglobeldjango/frontend
            dockerfile: Dockerfile.dev
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./services/envglobeldjango/frontend:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - main_net

    
    
