# Generated by Django 3.0.6 on 2020-05-31 11:51

import dashboard_item.models
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarditem',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='dashboarditem',
            name='viz_state',
        ),
        migrations.AddField(
            model_name='dashboarditem',
            name='query',
            field=django_mysql.models.JSONField(default=dashboard_item.models.my_default),
        ),
        migrations.AddField(
            model_name='dashboarditem',
            name='xs',
            field=models.IntegerField(null=True),
        ),
    ]
