# Generated by Django 3.0.6 on 2020-05-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_item', '0002_auto_20200531_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarditem',
            name='chart_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
