# Generated by Django 3.0.6 on 2020-05-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_item', '0002_auto_20200531_1151'),
        ('dashboard', '0002_dashboard_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='item',
            field=models.ManyToManyField(blank=True, to='dashboard_item.DashboardItem'),
        ),
    ]
